version: '3.8'
services:
  db:
    image: gvenzl/oracle-free:23-slim
    container_name: vidriera_oracle_db
    environment:
      ORACLE_PASSWORD: root
      APP_USER: vidriera_user
      APP_USER_PASSWORD: vidriera123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: vidriera_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=100.114.112.47
      - DB_PORT=1521
      - DB_USER=cba_vidriera
      - DB_PASSWORD=M1nisterio2026$$
      - PASSWORD=M1nisterio2026$$
      - DB_NAME=freepdb1
      - DB_SERVICE=freepdb1
      - DB_SERVICE_NAME=freepdb1
      - DB_DSN=100.114.112.47:1521/freepdb1
      - DB_CONNECTION=100.114.112.47:1521/freepdb1
      - JWT_SECRET_KEY=57af69b091b60bb557d8fce20f3c79b1bf36dac474e16d08d64f33f1bde51ffd
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=60

  frontend:
    build: ./frontend
    container_name: vidriera_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  oracle_data: