-- creacion del usuario / schema con contraseña
CREATE USER cba_vidriera IDENTIFIED BY "M1nisterio2026$" 
DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;

-- Permitir que el usuario se conecte y genere cosas basicas
GRANT CONNECT, RESOURCE TO cba_vidriera;

-- permitir almacen de datos
ALTER USER cba_vidriera QUOTA UNLIMITED ON users;

-- conexion a la base de datos
CONNECT cba_vidriera/M1nisterio2026$

CREATE TABLE representates (
	id_representante NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nombre_representante VARCHAR2(150) NOT null,
	apellido_representante VARCHAR2(150) NOT null,
	email_representante VARCHAR2(150) NOT null,
	contrasenia_representate VARCHAR2(256) NOT NULL, 
	n_telefono_representante VARCHAR2(22 CHAR),
	fecha_de_creacion DATE, -- el insert debe ser guardado con el formato
	-- 0 usuario
	-- 1 administrador
	rol INT(1) DEFAULT 0,
	--consltar, en que estado conviene, ponerlo en desactivado y pasarlo a activado cuado se verifique la cuenta, o dejarlo en activado
	estado INT(1),
	-- se le arma para checkear el estado? que sera una variacion entre 0 y 1 solamente? como tambien se le armaria a el mismo checkeo al rol 
	-- 3 estados, activa, baja y modificacion
	-- 				1		0		2
);

CREATE TABLE empresas(
	id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY,
	cuit NUMBER(11) NOT NULL,
	razon_social VARCHAR2(255) NOT NULL, 
	datos_publico JSON -- se le insertan valores con el formato json
);


-- DEFINICION DE LOCALIDADES
CREATE TABLE zonas(
	id_zona NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nombre_zona VARCHAR(250),
	CONSTRAINT pk_zonas PRIMARY KEY (id_zona)
);

CREATE TABLE departamentos(
	id_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nombre_departamento VARCHAR(250),
	id_zona NUMBER NOT NULL, -- Clave ajena
	CONSTRAINT pk_departamentos PRIMARY KEY (id_departamento),
    CONSTRAINT fk_deptos_zonas FOREIGN KEY (id_zona) 
        REFERENCES zonas(id_zona)
);

CREATE TABLE localidades( 
	id_localidad NUMBER GENERATED BY DEFAULT AS IDENTITY,
	nombre_localidad VARCHAR(250),
	id_departamento  NUMBER NOT NULL, 
   
    CONSTRAINT pk_localidades PRIMARY KEY (id_localidad),
    CONSTRAINT fk_localidades_deptos FOREIGN KEY (id_departamento) 
        REFERENCES departamentos(id_departamento)
);



/* Formas de filtrado 
 * SELECT nombre_departamento WHERE id_zona = 1 ORDER BY nombre_departamento;
 * 
 * 
 * 
 */