-- Tabla de noticias: la usan la sección pública "Novedades" (mapa/home)
-- y el nuevo módulo "Gestión de noticias" del dashboard admin.
--
-- Igual que empresas.datos_publico, el cuerpo puede ser largo (CLOB).
-- La imagen NO se guarda en la base como BLOB: se guarda en disco, en
-- backend/uploads/noticias/, y acá solo se persiste el nombre del
-- archivo (imagen_archivo, NULL si la noticia no tiene imagen). Ver
-- backend/api/v1/endpoints/noticias.py.
--
-- Correr después de bigbang.sql, contra el esquema cba_vidriera.

CREATE TABLE noticias (
	id_noticia              NUMBER GENERATED BY DEFAULT AS IDENTITY,
	titulo                  VARCHAR2(200) NOT NULL,
	cuerpo                  CLOB NOT NULL,
	imagen_archivo          VARCHAR2(300), -- nombre de archivo en backend/uploads/noticias/, NULL si no tiene imagen
	fecha_creacion          DATE DEFAULT SYSDATE NOT NULL,
	fecha_actualizacion     DATE,
	id_representante_autor  NUMBER, -- admin que la creó (ver require_admin() en security.py)
	-- 1 publicada, 0 dada de baja (soft delete)
	estado                  NUMBER(1) DEFAULT 1 NOT NULL,
	CONSTRAINT pk_noticias PRIMARY KEY (id_noticia),
	CONSTRAINT fk_noticias_autor FOREIGN KEY (id_representante_autor)
		REFERENCES representates(id_representante)
);

-- El listado público siempre ordena por fecha descendente (última
-- noticia primero): índice para que ese ORDER BY no sea un sort completo.
CREATE INDEX idx_noticias_fecha ON noticias (fecha_creacion DESC);
